application: u-arch
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /bootstrap
  static_dir: libs/bootstrap-2.3.2  
- url: /rbootstrap
  static_dir: libs/bootstrap-2.3.2-rtl
- url: /jquery
  static_dir: libs/jquery

- url: /he
  static_files: static/he/index.html
  upload: he/index.html
- url: /en
  static_files: static/en/index.html
  upload: en/index.html
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

  
- url: /.*
  script: main.application
  
  
libraries:
- name: jinja2
  version: latest
