application: frl-arch
version: test
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /libs
  static_dir: libs
- url: /populate
  static_dir: populate
- url: /webres
  static_dir: webres

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: main.application

builtins:
- remote_api: on
  
libraries:
- name: jinja2
  version: latest
